name: build
on:
  push

jobs:
  cabal:
    name: ${{ matrix.os }}-GHC${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ["8.10.4"]
        cabal: ["3.4.0.0"]

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: haskell/actions/setup@v1
      id: setup-haskell
      name: Set up Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct

    - name: cabal freeze
      run: |
        cabal freeze

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal build all

    - name: Test
      run: |
        cabal test abbotsbury:test:tests
