name: release-asset
on:
  push:
    tags:
      - 'v*'

# see: https://markkarpov.com/post/github-actions-for-haskell-ci.html
# see: http://taylor.fausak.me/2016/05/09/add-files-to-github-releases/

jobs:
  cabal:
    name: ${{ matrix.os }}-ghc${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ["8.10.4"]
        cabal: ["3.4.0.0"]

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: haskell/actions/setup@v1
      id: setup-haskell
      name: Set up Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: cabal update
      run: |
        cabal update

    - name: cabal freeze
      run: |
        cabal freeze

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: |
        cabal build all

    - name: Test
      run: |
        cabal test abbotsbury:test:tests

    - name: Install
      run: |
        mkdir bdist
        cabal install exe:abbot --install-method=copy --overwrite-policy=always --installdir=bdist

    - name: Get version number
      run: echo "::set-env name=VERSION::$(git tag -l --points-at HEAD | sed 's/^v//')"

    - name: Create release if everything succeeded
      if: ${{ success() }}
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: abbotsbury-v${{ env.VERSION }}
        draft: true
        prerelease: false

    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./dist/abbot
        asset_name: abbot-${{ env.VERSION }}-${{ runner.os }}-ghc-${{ matrix.ghc }}
        asset_content_type: application/octet-stream
